### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by mderouss** [bringItUpX/Tascam-US-122#1]
Doesn't work for me. Firstly, the script is wrong - 'tascam_loader.ihx' is not in '.', it's in usx2yloader. More importantly, running fxload just generates a error : 'can't modify CPUCS: Broken pipe'. There are some hints on the net that this could maybe be caused by an incorrect device id. I have a US-122MkII, not a US-122. But I wouldn't have expected that to make a difference.

**Comment by mderouss** [comment]
.... ah, but maybe it *does make a difference, because the /usr/share/alsa/firmware/usx2yloader/us122.conf file refers to an id of 8007, not 8021. Not sure I want to experiment by changing that until I have a way to revert.

**Comment by bringItUpX** [comment]
the MkII is a differernt one. The this script is for the normal us 122
